Repository openshift-knative/client, pull requests merged in 2023-09, with the labels that each got.

#245 Add helm binary to build image from GH
  openshift/ci-operator/build-image/Dockerfile
Labels: approved

#255 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: kind/sync-fork-to-upstream

#262 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: kind/sync-fork-to-upstream

#246 chore: sync CI PR is auto approved
  openshift/release/update-to-head.sh
Labels: lgtm, approved

#263 [release-v1.9] SRVCOM-2673: Update quarkus_version for kn-plugin-workflow
  hack/build.sh.d/kn-plugin-workflow.sh
Labels: lgtm, approved, ok-to-test

#264 [release-v1.9] Update func to include newer Quarkus version
  go.mod
  go.sum
  vendor/knative.dev/func/generate/zz_filesystem_generated.go
  vendor/modules.txt
Labels: lgtm, approved
