Repository openshift-knative/client, pull requests merged in 2023-07, with the labels that each got.

#195 [release-v1.9] Add ldflag flag for kn-event-plugin
  hack/build.sh.d/kn-plugin-event.sh
Labels: approved

#198 [SRVOCF-477] add default s2i builders.
  hack/build.sh.d/func.sh
Labels: lgtm, approved

#200 [release-v1.9] Update func to v1.10.1
  go.mod
  go.sum
  vendor/knative.dev/func/cmd/deploy.go
  vendor/knative.dev/func/cmd/environment.go
  vendor/knative.dev/func/cmd/root.go
  vendor/knative.dev/func/generate/zz_filesystem_generated.go
  vendor/knative.dev/func/pkg/functions/function.go
  vendor/knative.dev/func/pkg/knative/deployer.go
  vendor/knative.dev/func/pkg/pipelines/tekton/templates.go
  vendor/knative.dev/func/plugin/plugin.go
  vendor/modules.txt
Labels: lgtm, approved

#201 [release-v1.9] Update kn-workflow to v0.30.2
  go.mod
  go.sum
  openshift/release/kn.yaml
  vendor/github.com/kiegroup/kie-tools/packages/kn-plugin-workflow/pkg/command/deploy_undeploy_common.go
  vendor/modules.txt
Labels: lgtm, approved, ok-to-test

#202 [release-v1.9] Update kn-workflow to v0.30.3
  go.mod
  go.sum
  openshift/release/kn.yaml
  vendor/github.com/kiegroup/kie-tools/packages/kn-plugin-workflow/pkg/command/quarkus/convert.go
  vendor/modules.txt
Labels: lgtm, approved, ok-to-test

#205 remove spec file which maintain at p12n/config
  openshift-serverless-clients.spec
Labels: lgtm, approved
