Repository openshift-knative/client, pull requests merged in 2025-02, with the labels that each got.

#567 [release-v1.16] Update Konflux configurations
  .tekton/docker-build.yaml
  openshift/ci-operator/knative-images/kn/Dockerfile
Labels: lgtm, approved, needs-ok-to-test

#571 Fix s-o setup
  openshift/e2e-common.sh
  openshift/e2e-tests-openshift.sh
Labels: lgtm, approved

#564 [release-v1.17] Update Konflux configurations
  .github/workflows/dependabot-deps.yaml
  .konflux/applications/serverless-operator-137/components/imagerepositories/kn-client-cli-artifacts-117.yaml
  .konflux/applications/serverless-operator-137/components/imagerepositories/kn-client-kn-117.yaml
  .konflux/applications/serverless-operator-137/components/imagerepositories/kn-client-test-grpc-ping-117.yaml
  .konflux/applications/serverless-operator-137/components/imagerepositories/kn-client-test-helloworld-117.yaml
  .konflux/applications/serverless-operator-137/components/imagerepositories/kn-client-test-servingcontainer-117.yaml
  .konflux/applications/serverless-operator-137/components/imagerepositories/kn-client-test-sidecarcontainer-117.yaml
  .konflux/applications/serverless-operator-137/components/kn-client-cli-artifacts-117.yaml
  .konflux/applications/serverless-operator-137/components/kn-client-kn-117.yaml
  .konflux/applications/serverless-operator-137/components/kn-client-test-grpc-ping-117.yaml
  .konflux/applications/serverless-operator-137/components/kn-client-test-helloworld-117.yaml
  .konflux/applications/serverless-operator-137/components/kn-client-test-servingcontainer-117.yaml
  .konflux/applications/serverless-operator-137/components/kn-client-test-sidecarcontainer-117.yaml
  .tekton/docker-build.yaml
  .tekton/kn-client-cli-artifacts-117-pull-request.yaml
  .tekton/kn-client-cli-artifacts-117-push.yaml
  .tekton/kn-client-kn-117-pull-request.yaml
  .tekton/kn-client-kn-117-push.yaml
  .tekton/kn-client-test-grpc-ping-117-pull-request.yaml
  .tekton/kn-client-test-grpc-ping-117-push.yaml
  .tekton/kn-client-test-helloworld-117-pull-request.yaml
  .tekton/kn-client-test-helloworld-117-push.yaml
  .tekton/kn-client-test-servingcontainer-117-pull-request.yaml
  .tekton/kn-client-test-servingcontainer-117-push.yaml
  .tekton/kn-client-test-sidecarcontainer-117-pull-request.yaml
  .tekton/kn-client-test-sidecarcontainer-117-push.yaml
  openshift/ci-operator/knative-images/kn/Dockerfile
Labels: needs-ok-to-test
