Repository openshift-knative/client, pull requests merged in 2025-03, with the labels that each got.

#562 [main] Update dependabot configurations
  .github/dependabot.yml
  .github/workflows/dependabot-deps.yaml
  renovate.json
Labels: lgtm, approved, needs-ok-to-test

#603 Refactor CI setup
  openshift/e2e-common.sh
  openshift/e2e-tests-openshift.sh
Labels: lgtm, approved

#566 [release-v1.15] Update Konflux configurations
  .github/workflows/dependabot-deps.yaml
  .tekton/docker-build.yaml
  .tekton/kn-client-cli-artifacts-115-pull-request.yaml
  .tekton/kn-client-cli-artifacts-115-push.yaml
  .tekton/kn-client-kn-115-pull-request.yaml
  .tekton/kn-client-kn-115-push.yaml
  .tekton/kn-client-test-grpc-ping-115-pull-request.yaml
  .tekton/kn-client-test-grpc-ping-115-push.yaml
  .tekton/kn-client-test-helloworld-115-pull-request.yaml
  .tekton/kn-client-test-helloworld-115-push.yaml
  .tekton/kn-client-test-servingcontainer-115-pull-request.yaml
  .tekton/kn-client-test-servingcontainer-115-push.yaml
  .tekton/kn-client-test-sidecarcontainer-115-pull-request.yaml
  .tekton/kn-client-test-sidecarcontainer-115-push.yaml
  openshift/ci-operator/knative-images/kn/Dockerfile
Labels: lgtm, needs-ok-to-test

#625 [release-v1.15] Update Konflux configurations
  .tekton/docker-build.yaml
  openshift/ci-operator/knative-images/kn/Dockerfile
Labels: lgtm, approved

#626 [release-v1.15] Update event sender ref 1.35.1
  openshift/ci-operator/knative-images/kn/Dockerfile
Labels: lgtm, approved, ok-to-test

#627 [release-v1.15] Update github.com/golang-jwt/jwt/v4 to v4.5.2
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: lgtm, approved

#629 [release-v1.15] Run `make generate-release`
  openshift/ci-operator/knative-images/kn/Dockerfile
Labels: lgtm, approved
