Repository openshift-knative/client, pull requests merged in 2025-04, with the labels that each got.

#635 [release-v1.15] Update func-util image
  openshift/ci-operator/knative-images/kn/Dockerfile
Labels: approved

#636 [release-v1.15] Update event-sender image
  openshift/ci-operator/knative-images/kn/Dockerfile
Labels: lgtm, approved

#569 [release-v1.16] Update Konflux configurations
  .github/workflows/dependabot-deps.yaml
  .konflux/applications/serverless-operator-136/components/kn-client-cli-artifacts-116.yaml
  .konflux/applications/serverless-operator-136/components/kn-client-kn-116.yaml
  .konflux/applications/serverless-operator-136/components/kn-client-test-grpc-ping-116.yaml
  .konflux/applications/serverless-operator-136/components/kn-client-test-helloworld-116.yaml
  .konflux/applications/serverless-operator-136/components/kn-client-test-servingcontainer-116.yaml
  .konflux/applications/serverless-operator-136/components/kn-client-test-sidecarcontainer-116.yaml
  .tekton/docker-build.yaml
  .tekton/kn-client-cli-artifacts-116-pull-request.yaml
  .tekton/kn-client-cli-artifacts-116-push.yaml
  .tekton/kn-client-kn-116-pull-request.yaml
  .tekton/kn-client-kn-116-push.yaml
  .tekton/kn-client-test-grpc-ping-116-pull-request.yaml
  .tekton/kn-client-test-grpc-ping-116-push.yaml
  .tekton/kn-client-test-helloworld-116-pull-request.yaml
  .tekton/kn-client-test-helloworld-116-push.yaml
  .tekton/kn-client-test-servingcontainer-116-pull-request.yaml
  .tekton/kn-client-test-servingcontainer-116-push.yaml
  .tekton/kn-client-test-sidecarcontainer-116-pull-request.yaml
  .tekton/kn-client-test-sidecarcontainer-116-push.yaml
  openshift/ci-operator/knative-images/kn/Dockerfile
Labels: ok-to-test

#646 Update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: lgtm, approved

#648 [release-v1.16] Bump golang images
  openshift/ci-operator/build-image/Dockerfile
  openshift/ci-operator/knative-images/kn/Dockerfile
  openshift/ci-operator/knative-test-images/grpc-ping/Dockerfile
  openshift/ci-operator/knative-test-images/helloworld/Dockerfile
  openshift/ci-operator/knative-test-images/servingcontainer/Dockerfile
  openshift/ci-operator/knative-test-images/sidecarcontainer/Dockerfile
  openshift/generate.sh
Labels: lgtm, approved

#649 [release-v1.16] Update Konflux configurations
  .tekton/docker-build.yaml
Labels: lgtm

#668 [release-v1.18] Add dockerfile generator
  openshift/ci-operator/build-image/Dockerfile
  openshift/ci-operator/knative-images/kn/Dockerfile
  openshift/ci-operator/knative-test-images/helloworld/Dockerfile
  openshift/ci-operator/source-image/Dockerfile
  openshift/generate.sh
  openshift/images.yaml
Labels: lgtm, approved

#676 Update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: approved

#580 [release-v1.17] Update Konflux configurations
  .tekton/docker-build.yaml
  .tekton/kn-client-cli-artifacts-117-pull-request.yaml
  .tekton/kn-client-cli-artifacts-117-push.yaml
  .tekton/kn-client-kn-117-pull-request.yaml
  .tekton/kn-client-kn-117-push.yaml
  .tekton/kn-client-test-grpc-ping-117-pull-request.yaml
  .tekton/kn-client-test-grpc-ping-117-push.yaml
  .tekton/kn-client-test-helloworld-117-pull-request.yaml
  .tekton/kn-client-test-helloworld-117-push.yaml
  .tekton/kn-client-test-servingcontainer-117-pull-request.yaml
  .tekton/kn-client-test-servingcontainer-117-push.yaml
  .tekton/kn-client-test-sidecarcontainer-117-pull-request.yaml
  .tekton/kn-client-test-sidecarcontainer-117-push.yaml
  openshift/ci-operator/knative-images/kn/Dockerfile
Labels: needs-ok-to-test

#678 add rudyredhat1 to owner list
  OWNERS_ALIASES
Labels: lgtm, approved
