Repository openshift-knative/client, pull requests merged in 2025-01, with the labels that each got.

#560 [release-v1.15] Update kn-plugin-event SHA to latest 1.15 version
  openshift/ci-operator/knative-images/kn/Dockerfile
Labels: lgtm, approved

#561 [main] Update dependabot configurations
  .github/dependabot.yml
  .github/workflows/dependabot-deps.yaml
Labels: lgtm, approved, ok-to-test

#556 [release-v1.15] Add Konflux configurations
  .konflux/applications/serverless-operator-135/serverless-operator-135.yaml
  .konflux/applications/serverless-operator-135/tests/ec-test.yaml
  .konflux/applications/serverless-operator-135/tests/override-snapshot-ec-test.yaml
  openshift/ci-operator/build-image/Dockerfile
  openshift/ci-operator/knative-images/kn/Dockerfile
Labels: lgtm, needs-ok-to-test
